image: $CI_REGISTRY/sysadmin/docker-and-compose:stable
services:
  - docker:stable-dind

stages:
  - test
  - build

variables:
  VIEW: default
  PROXY: https://search-test.obvsg.at:443
  OBV_CENTRAL: primo-explore-obv-central

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker-compose pull

test_job:
  stage: test
  script:
    - chown -R 1000:1000 . # devenv runs as node user
    - docker-compose run devenv gulp install-primo-node-modules --view $VIEW --proxy $PROXY
    - docker-compose run devenv /bin/sh -c "cd primo-explore/custom/$VIEW && npm run csslint"
    - docker-compose run devenv /bin/sh -c "cd primo-explore/custom/$VIEW && npm run eslint"
  tags:
    - docker-build

build_job:
  stage: build
  script:
    - mkdir -p ../$OBV_CENTRAL/js ../$OBV_CENTRAL/css
    - wget -q $PROXY/primo-explore/custom/CENTRAL_PACKAGE/js/custom.js -O ../$OBV_CENTRAL/js/custom.js
    - wget -q $PROXY/primo-explore/custom/CENTRAL_PACKAGE/css/custom1.css -O ../$OBV_CENTRAL/css/custom1.css
    - chown -R 1000:1000 . ../$OBV_CENTRAL
    - docker-compose run devenv gulp --view $VIEW --proxy $PROXY --browserify --useScss --series install-primo-node-modules app-css create-package
  tags:
    - docker-build
  artifacts:
    paths:
    - $VIEW.zip
