version: '3'

services:

  devenv:
    image: ${CI_REGISTRY}/primo/frontend/primo-explore-devenv-docker
#   image: uleodolter/primo-explore-devenv-docker
    environment:
      PROXY: ${PROXY}
      VIEW: ${VIEW}
      GULP_OPTIONS: ${GULP_OPTIONS}
      DEVENV_UID: ${DEVENV_UID:-1000}
      DEVENV_GID: ${DEVENV_GID:-1000}
    ports:
      - 8003:8003
      - 3001:3001
    volumes:
      - ./:/app/primo-explore-devenv/packages
      - ./:/app/primo-explore-devenv/primo-explore/custom/${VIEW}
      - ../primo-explore-obv-central:/app/primo-explore-devenv/primo-explore/custom/CENTRAL_PACKAGE
